#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <locale>
main()
{
	printf("Alo Mundo!!");
	
	float qtd_lata, qtd_litro custo_total,custo_ind, raio, altura, area;
	
	printf("Digite a altura do cilindro: ");
	scanf("%f", altura);
	printf("Digite o raio do cilindro: ");
	scanf("%f", raio);
	
	
	
	
	
	
	
	qtd_litro = area/3;
	
	qtd_lata = qtd_litro/5;
	
	custo_total = qtd_lata *20; 
	

	system("PAUSE");
}